const anotherOneDrink = {
  drinks: [
    {
      'idDrink': '17837',
      'strDrink': 'Adam',
      'strDrinkAlternate': null,
      'strDrinkES': 'Adam',
      'strDrinkDE': 'Adam',
      'strDrinkFR': 'Adam',
      'strDrinkZH-HANS': '亚当',
      'strDrinkZH-HANT': '亞當',
      'strTags': 'Alcoholic,Holiday',
      'strVideo': null,
      'strCategory': 'Ordinary Drink',
      'strIBA': null,
      'strAlcoholic': 'Alcoholic',
      'strGlass': 'Cocktail glass',
      'strInstructions': 'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.',
      'strInstructionsES': null,
      'strInstructionsDE': 'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.',
      'strInstructionsFR': null,
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      'strDrinkThumb': 'https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg',
      'strIngredient1': 'Dark rum',
      'strIngredient2': 'Lemon juice',
      'strIngredient3': 'Grenadine',
      'strIngredient4': null,
      'strIngredient5': null,
      'strIngredient6': null,
      'strIngredient7': null,
      'strIngredient8': null,
      'strIngredient9': null,
      'strIngredient10': null,
      'strIngredient11': null,
      'strIngredient12': null,
      'strIngredient13': null,
      'strIngredient14': null,
      'strIngredient15': null,
      'strMeasure1': '2 oz ',
      'strMeasure2': '1 oz ',
      'strMeasure3': '1 tsp ',
      'strMeasure4': null,
      'strMeasure5': null,
      'strMeasure6': null,
      'strMeasure7': null,
      'strMeasure8': null,
      'strMeasure9': null,
      'strMeasure10': null,
      'strMeasure11': null,
      'strMeasure12': null,
      'strMeasure13': null,
      'strMeasure14': null,
      'strMeasure15': null,
      'strCreativeCommonsConfirmed': 'Yes',
      'dateModified': '2016-09-02 11:29:29'
    },
  ],
}

export default anotherOneDrink;
